backend:
  name: github
  repo: NdT3Development/NdT3Development.github.io
  branch: master
  site_domain: www.ndt3.me
media_folder: "images/uploads"
collections:
  - name: "redirects" # Used in routes, e.g. /admin/collections/blog
    label: "Redirects" # Used in the UI
    folder: "r" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "r"}
      - {label: "Redirect To", name: "r", widget: "string"}
      - {label: "Short URL Code", name: "title", widget: "string"}
      - {label: "Comment", name: "comment", widget: "string"}
